# Generated by Django 3.0.7 on 2021-05-19 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentimen_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbproduct',
            options={'managed': False, 'ordering': ('nama_product',)},
        ),
    ]
